# Generated by Django 6.0.2 on 2026-02-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('birth_year', models.CharField(blank=True, max_length=50)),
                ('death_year', models.CharField(blank=True, max_length=50)),
                ('madhhab', models.CharField(blank=True, max_length=100)),
                ('birth_place', models.CharField(blank=True, max_length=200)),
                ('biography', models.TextField()),
                ('teachers', models.TextField(blank=True)),
                ('students', models.TextField(blank=True)),
                ('famous_books', models.TextField(blank=True)),
                ('notable_quotes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
