# Generated by Django 6.0.2 on 2026-02-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='scholar',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='scholars/'),
        ),
        migrations.AddField(
            model_name='scholar',
            name='short_bio',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
