# Generated by Django 6.0.2 on 2026-02-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0003_scholar_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholar',
            options={'permissions': [('can_publish', 'Can publish scholar')]},
        ),
    ]
